---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=3000
      - TZ=America/Chicago
    volumes:
      - /mnt/container/appfs/radarr:/config
      - /mnt/storage/share/movie:/movie 
      - /mnt/storage/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
