version: '0.1'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=3000
      - TZ=America/Chicago
      - WEBUI_PORT=18080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/container/appfs/qbittorrent:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 18080:18080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
