version: '0.1'

services:
  radarr:
    image: linuxserver/radarr
    deploy:
      replicas: 3
    ports:
      - "7878:7878"
    environment:
      - PUID=1000  # Replace with your user ID
      - PGID=1000  # Replace with your group ID
      - TZ=America/Chicago  # Set timezone to America/Chicago
    volumes:
      - /opt/docker/stack/media/radarr/config:/config
      #- /movies:/movies
      #- /downloads:/downloads
    networks:
      - media_tools

networks:
  media_tools:
    driver: overlay
    attachable: true
